image: mcr.microsoft.com/dotnet/sdk:6.0

stages:
  - build
  - test

build:
  stage: build
  needs: []
  script:
    - 'dotnet build'

test:
  stage: test
  needs: []
  script:
    - 'dotnet test --test-adapter-path:. --logger:"junit;LogFilePath=..\artifacts\{assembly}-test-result.xml;MethodFormat=Class;FailureBodyFormat=Verbose"'
  artifacts:
    when: always
    paths:
      - ./**/*test-result.xml
    reports:
      junit:
        - ./**/*test-result.xml
